# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84604fb91d14f2ddcb1b5e4c897a8f41891000792370566ea664ea64c0765b46eb1310bfb1129303afad453133c28c2e7c85a1c9ab42017704d42041f4967f93

test:
  secret_key_base: 77ede82f7ba5689637c0e75fa51e7a3539dc64d4ebc9138c89ab76011a0b80c4c2f48c57c06866bf5de17b7af5be939b974ace6df71b4c2d81f58bd6415bbb99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
